### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by 8483** [tbluemel/rtf.js#57]
I am trying to use RTFJS in Node, and I get the following error...

```bash
Error
    at new RTFJSError (/mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:318:19)
    at /mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:208:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'RTFJSError',
  message: ReferenceError: document is not defined
      at Renderer.buildDom (/mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:10305:28)
      at /mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:206:36
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  stack: 'Error\n' +
    '    at new RTFJSError (/mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:318:19)\n' +
    '    at /mnt/c/ivan/lab/catalogue/node_modules/rtf.js/dist/RTFJS.bundle.js:208:19\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
```

Here's the code...

```js
const RTFJS = require("../../node_modules/rtf.js/dist/RTFJS.bundle.js");

const rtf = `{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}
            {\\*\\generator Msftedit 5.41.21.2510;}\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\lang9\\f0\\fs22 This \\fs44 is \\fs22 a \\b simple \\ul one \\i paragraph \\ulnone\\b0 document\\i0 .\\par
            }`;

            function stringToArrayBuffer(string) {
                var buffer = new ArrayBuffer(string.length);
                var bufferView = new Uint8Array(buffer);
                for (var i = 0; i < string.length; i++) {
                    bufferView[i] = string.charCodeAt(i);
                }
                return buffer;
            }

            RTFJS.loggingEnabled(false);
            // WMFJS.loggingEnabled(false);
            // EMFJS.loggingEnabled(false);

            const doc = new RTFJS.Document(stringToArrayBuffer(rtf));

            const meta = doc.metadata();
            doc
                .render()
                .then(function (htmlElements) {
                    console.log(meta);
                    console.log(htmlElements);
                })
                .catch(error => console.error(error));
```

**Comment by zoehneto** [comment]
RTFJS requires the DOM to work so you have to use jsdom if you want to use it in node. See the [getting started guide](https://github.com/tbluemel/rtf.js/blob/master/GETTING_STARTED.md#node-using-jsdom) for further details.

**Comment by 8483** [comment]
Ah, I see...

Can you please tell me what I'm doing wrong? I can't extract the html.

[CodeSandbox](https://codesandbox.io/s/serene-kilby-z7hgi?file=/src/index.js:0-1921)

```js
// const RTFJS = require("rtf.js").RTFJS;
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

function stringToArrayBuffer(string) {
  var buffer = new ArrayBuffer(string.length);
  var bufferView = new Uint8Array(buffer);
  for (var i = 0; i < string.length; i++) {
    bufferView[i] = string.charCodeAt(i);
  }
  return buffer;
}

exports.runRtfjs = function(rtf, callback, errorCallback) {
  const virtualConsole = new jsdom.VirtualConsole();
  virtualConsole.sendTo(console);

  var dom = new JSDOM(
    `
  <script src="./node_modules/rtf.js/dist/RTFJS.bundle.js"></script>

  <script>

      RTFJS.loggingEnabled(false);

      try {
          const doc = new RTFJS.Document(rtfFile);

          const meta = doc.metadata();
          doc
            .render()
            .then(function(htmlElements) {

              const div = document.createElement("div");
              div.append(...htmlElements);

              window.done(meta, div.innerHTML);

          }).catch(error => window.onerror(error))
      } catch (error){
          window.onerror(error)
      }
  </script>
  `,
    {
      resources: "usable",
      runScripts: "dangerously",
      url: "file://" + __dirname + "/",
      virtualConsole,
      beforeParse(window) {
        const rtf = `{\\rtf1\\ansi\\ansicpg1251\\deff0{\\fonttbl{\\f0\\fnil\\fcharset204 Tahoma;}{\\f1\\fnil\\fcharset0 Tahoma;}{\\f2\\fnil Tahoma;}}  \\viewkind4\\uc1\\pard\\lang1071\\f0\\fs16\\'c3\\'d0\\'c8\\'cd\\'c0\\'c3\\'d0\\'ce \\'c4\\'ce\\'ce\\'c5\\'cb \\'d1\\'ca\\'ce\\'cf\\'a3\\'c5 (\\'ea\\'ee\\'ec\\'e8\\'ed\\'f2\\'e5\\'ed\\'f2\\lang1033\\f1 :\\lang1071\\f0 1024)\\f2\\par  }  `;

        window.rtfFile = stringToArrayBuffer(rtf);
        window.done = function(meta, html) {
          console.log(html);
          callback(meta, html);
        };
        window.onerror = function(error) {
          errorCallback(error);
        };
      }
    }
  );
};

```

**Comment by zoehneto** [comment]
You are hard coding the rtf but you never actually call the function which would generate the html. To use the sample as intended you would have to do something like this (not tested, but should probably work):

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

function stringToArrayBuffer(string) {
  var buffer = new ArrayBuffer(string.length);
  var bufferView = new Uint8Array(buffer);
  for (var i = 0; i < string.length; i++) {
    bufferView[i] = string.charCodeAt(i);
  }
  return buffer;
}

function runRtfjs(rtf, callback, errorCallback) {
  const virtualConsole = new jsdom.VirtualConsole();
  virtualConsole.sendTo(console);

  var dom = new JSDOM(
    `
  <script src="./node_modules/rtf.js/dist/RTFJS.bundle.js"></script>

  <script>

      RTFJS.loggingEnabled(false);

      try {
          const doc = new RTFJS.Document(rtfFile);

          const meta = doc.metadata();
          doc
            .render()
            .then(function(htmlElements) {

              const div = document.createElement("div");
              div.append(...htmlElements);

              window.done(meta, div.innerHTML);

          }).catch(error => window.onerror(error))
      } catch (error){
          window.onerror(error)
      }
  </script>
  `,
    {
      resources: "usable",
      runScripts: "dangerously",
      url: "file://" + __dirname + "/",
      virtualConsole,
      beforeParse(window) {
        window.rtfFile = stringToArrayBuffer(rtf);
        window.done = function(meta, html) {
          callback(meta, html);
        };
        window.onerror = function(error) {
          errorCallback(error);
        };
      }
    }
  );
};

const rtf = `{\\rtf1\\ansi\\ansicpg1251\\deff0{\\fonttbl{\\f0\\fnil\\fcharset204 Tahoma;}{\\f1\\fnil\\fcharset0 Tahoma;}{\\f2\\fnil Tahoma;}}  \\viewkind4\\uc1\\pard\\lang1071\\f0\\fs16\\'c3\\'d0\\'c8\\'cd\\'c0\\'c3\\'d0\\'ce \\'c4\\'ce\\'ce\\'c5\\'cb \\'d1\\'ca\\'ce\\'cf\\'a3\\'c5 (\\'ea\\'ee\\'ec\\'e8\\'ed\\'f2\\'e5\\'ed\\'f2\\lang1033\\f1 :\\lang1071\\f0 1024)\\f2\\par  }  `;

runRtfjs(rtf, (meta, html) => console.log(html), () => {});
```

Note: this is a code sample for nodejs. It will not work with CodeSandbox, as CodeSandbox executes the code in your browser instead of in a node environment.

**Comment by 8483** [comment]
Riiiiight... Finally got it working. Thank you so much.  

The documentation could be a bit clearer about this. :)

**Comment by zoehneto** [comment]
That's a fair point, I've updated the node example to produce a result straight away (like the other examples).
